### ISSUE TITLE
OUTDATED

### ISSUE THREAD

**Issue by LockedThread** [rmayobre/PopOs-VFIO-Tutorial#1]
This tutorial is outdated, and I suggest no one use this from now on. After following the instructions vigorously I had utterly fucked my graphics card, luckily I was doing this on my test bench and not on my main PC. I hope the @rmayobre either takes down this repository, archives it, or updates it, so it works.

**Comment by rmayobre** [comment]
Hi @LockedThread , I'm sorry that happened to you. I hadn't updated the VFIO attachment process in a while because that was the standard way to perform a passthrough since the previous LTS. Up until this point I had not attempted VFIO on a Ubuntu Distribution running 20.04 LTS and for a while I was messing around with Fedora. Originally I created this Wiki to help me keep reference on how to do these things and when I saw people viewing my guide I expanded to the Virt-manager documentation and neglected going back to trying the VFIO and see if it worked still.

It occurred to me this morning while trying out Pop os 20.04 that Ubuntu had removed VFIO as module and instead made it built-in to the kernel. This makes common VFIO passthrough much easier. Please check out the updated WIki page as I have marked the older method a deprecated (although it can still be used if you apply a custom kernel with VFIO as a module) and the new page marked for 20.04 LTS.

If you have anymore troubles, try this tutorial I found on [YouTube](https://www.youtube.com/watch?v=HBEqGHCd8hk). He provides a Shell script that performs most of the work for you.

Hopefully your GPU isn't permanently broken from this experience, as I've never heard this process permanently bricking a GPU before. I ran the previous tutorial I had written down and did not find my GPU to be broken. 

If you have anymore questions, please reach out to me or continue on this thread as it is important to provide as much information to anyone who wants to learn how to perform a VFIO passthrough.

**Comment by rmayobre** [comment]
Hi @LockedThread , is there is anything else you like to mention? Otherwise I'm going to close this issue.
